//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorJournal.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuratorCharacteristic
    {
        public int CharacteristicId { get; set; }
        public int StudentId { get; set; }
        public int CuratorId { get; set; }
        public string Characteristic { get; set; }
        public System.DateTime DateCreated { get; set; }
    
        public virtual Curator Curator { get; set; }
        public virtual Student Student { get; set; }
    }
}
