//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorJournal.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class IndividualWork
    {
        public int IndividualWorkId { get; set; }
        public bool IsStudent { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Topic { get; set; }
        public string Decision { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Parent Parent { get; set; }
        public virtual Student Student { get; set; }
    }
}
