//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorJournal.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CuratorJournalEntities : DbContext
    {
        public CuratorJournalEntities()
            : base("name=CuratorJournalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClassHour> ClassHour { get; set; }
        public virtual DbSet<Curator> Curator { get; set; }
        public virtual DbSet<CuratorCharacteristic> CuratorCharacteristic { get; set; }
        public virtual DbSet<GroupPost> GroupPost { get; set; }
        public virtual DbSet<Hobby> Hobby { get; set; }
        public virtual DbSet<IndividualWork> IndividualWork { get; set; }
        public virtual DbSet<Parent> Parent { get; set; }
        public virtual DbSet<ParentMeeting> ParentMeeting { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<Qualification> Qualification { get; set; }
        public virtual DbSet<SocialStatus> SocialStatus { get; set; }
        public virtual DbSet<Specification> Specification { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<StudentClassHour> StudentClassHour { get; set; }
        public virtual DbSet<StudentInDormitory> StudentInDormitory { get; set; }
        public virtual DbSet<StudyGroup> StudyGroup { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TeacherCategory> TeacherCategory { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
