//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorJournal.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParentMeeting
    {
        public int MeetingId { get; set; }
        public int StudyGroupId { get; set; }
        public int Visited { get; set; }
        public int NotVisitedWithReason { get; set; }
        public int NotVisited { get; set; }
        public string Topic { get; set; }
        public string Decision { get; set; }
    
        public virtual StudyGroup StudyGroup { get; set; }
    }
}
