//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorJournal.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudyGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudyGroup()
        {
            this.ParentMeeting = new HashSet<ParentMeeting>();
            this.Student = new HashSet<Student>();
        }
    
        public int StudyGroupId { get; set; }
        public string SpecificationAbbreviation { get; set; }
        public string QualificationAbbreviation { get; set; }
        public int Course { get; set; }
        public System.DateTime DateCreate { get; set; }
        public bool IsBuget { get; set; }
        public string FullName { get; set; }
        public int CuratorId { get; set; }
    
        public virtual Curator Curator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParentMeeting> ParentMeeting { get; set; }
        public virtual Qualification Qualification { get; set; }
        public virtual Specification Specification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Student { get; set; }
    }
}
