//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuratorJournal.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentClassHour
    {
        public int ClassHourId { get; set; }
        public int StudentId { get; set; }
        public bool IsVisited { get; set; }
    
        public virtual ClassHour ClassHour { get; set; }
        public virtual Student Student { get; set; }
    }
}
